name: Sync to GitLab

on:
  push:
    branches:
      - main  # spustí se při pushi na main, snad

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        

      - name: Push to GitLab
        env:
          GITLAB_USERNAME: Wolfy141
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Sync Bot"

          git remote add gitlab https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@gitlab.com/${GITLAB_USERNAME}/dbs2_projekt.git
          git push --force gitlab main